// Global types
export const ON_LOADING = 'ON_LOADING';
export const SHOW_ALERT = 'SHOW_ALERT';
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
export const GET_ROLES = 'GET_ROLES';
export const GET_US_STATES = 'GET_US_STATES';

// Auth types
export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const LOGOUT = 'LOGOUT';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

// User types
export const GET_USERS = 'GET_USERS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const DELETE_USER = 'DELETE_USER';


// Customer Types
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMERS_ERROR = 'GET_CUSTOMERS_ERROR';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_CUSTOMER_ERROR = 'CREATE_CUSTOMER_ERROR';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

// Projects
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';
export const GET_PROJECT = 'GET_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_ERROR = 'UPDATE_PROJECT_ERROR';
export const DELETE_PROJECT = 'DELETE_PROJECT';

// Reports
export const GET_REPORTS = 'GET_REPORTS';
export const GET_REPORTS_ERROR = 'GET_REPORTS_ERROR';
export const CREATE_REPORT = 'CREATE_REPORT';
export const CREATE_REPORT_ERROR = 'CREATE_REPORT_ERROR';
export const GET_REPORT = 'GET_REPORT';
export const UPDATE_REPORT = 'UPDATE_REPORT';
export const UPDATE_REPORT_ERROR = 'UPDATE_REPORT_ERROR';
export const DELETE_REPORT = 'DELETE_REPORT';


// Patient types
export const GET_PATIENT_TAGS = 'GET_PATIENT_TAGS';
export const GET_PATIENT_TAGS_ERROR = 'GET_PATIENT_TAGS';
export const GET_PATIENTS = 'GET_PATIENTS';
export const GET_PATIENTS_ERROR = 'GET_PATIENTS_ERROR';
export const CREATE_PATIENT = 'CREATE_PATIENT';
export const CREATE_PATIENT_ERROR = 'CREATE_PATIENT_ERROR';
export const GET_PATIENT = 'GET_PATIENT';
export const UPDATE_PATIENT = 'UPDATE_PATIENT';
export const UPDATE_PATIENT_ERROR = 'UPDATE_PATIENT_ERROR';
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const STORE_PATIENT = 'STORE_PATIENT';

// Product types
export const GET_CATEGORIES_LEVEL_1 = 'GET_CATEGORIES_LEVEL_1';
export const GET_CATEGORIES_LEVEL_2 = 'GET_CATEGORIES_LEVEL_2';
export const GET_CATEGORIES_LEVEL_3 = 'GET_CATEGORIES_LEVEL_3';
export const GET_PRODUCT_TYPES = 'GET_PRODUCT_TYPES';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';

export const GET_ORDER_STATUS = 'GET_ORDER_STATUS';
export const GET_ORDER_DELIVERIES = 'GET_ORDER_DELIVERIES';
export const GET_ORDER_RECURRENCES = 'GET_ORDER_RECURRENCES';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDER = 'GET_ORDER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR';
export const ORDER_ADD_PRODUCT = 'ORDER_ADD_PRODUCT';
export const ORDER_ADD_PRODUCT_ERROR = 'ORDER_ADD_PRODUCT_ERROR';
export const ORDER_UPDATE_PRODUCT = 'ORDER_UPDATE_PRODUCT';
export const ORDER_UPDATE_PRODUCT_ERROR = 'ORDER_UPDATE_PRODUCT_ERROR';
export const ORDER_REMOVE_PRODUCT = 'ORDER_REMOVE_PRODUCT';

export const GET_EXPIRATIONS = 'GET_EXPIRATIONS';
export const UPDATE_EXPIRATION = 'UPDATE_EXPIRATION';

export const GET_CALL_CUSTOMERS = 'GET_CALL_CUSTOMERS';
export const UPDATE_CALL_CUSTOMER = 'UPDATE_CALL_CUSTOMER';

export const GET_CHECK_ELIGIBILITIES = 'GET_CHECK_ELIGIBILITIES';
export const UPDATE_CHECK_ELIGIBILITY = 'UPDATE_CHECK_ELIGIBILITY';

export const GET_SHIPPING_STATUS = 'GET_SHIPPING_STATUS';

export const GET_REMITTANCE = 'GET_REMITTANCE';

export const HANDLE_FORM = 'HANDLE_FORM';
export const SET_CURRENT_FORM = 'SET_CURRENT_FORM';
