// Global types
export const ON_LOADING = 'ON_LOADING';
export const SHOW_ALERT = 'SHOW_ALERT';
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
export const GET_ROLES = 'GET_ROLES';
export const GET_STATES = 'GET_STATES';
export const CHANGE_OPEN_MENU = 'CHANGE_OPEN_MENU';
export const CHANGE_SELECTED_MENU = 'CHANGE_SELECTED_MENU';
export const GET_ITEM_STATES = 'GET_ITEM_STATES';
export const LOADED_CATEGORIES = 'LOADED_CATEGORIES';

// Auth types
export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const LOGOUT = 'LOGOUT';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

// User types
export const GET_USERS = 'GET_USERS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const DELETE_USER = 'DELETE_USER';


// Customer Types
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMER_SELECTED = 'GET_CUSTOMER_SELECTED';
export const GET_CUSTOMERS_ERROR = 'GET_CUSTOMERS_ERROR';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const CREATE_CUSTOMER_ERROR = 'CREATE_CUSTOMER_ERROR';
export const GET_CUSTOMER = 'GET_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

// Projects
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const GET_TAGS = 'GET_TAGS';
export const GET_USERS_PROJECT = 'GET_USERS_PROJECT';
export const ADD_USER_PROJECT = 'ADD_USER_PROJECT';
export const DELETE_USER_PROJECT = 'DELETE_USER_PROJECT';
export const GET_STRUCTURE_TYPES = 'GET_STRUCTURE_TYPES';
export const GET_SPAN_TYPES = 'GET_SPAN_TYPES';
export const GET_INSPECTIONS_PROJECT = 'GET_INSPECTIONS_PROJECT';
export const GET_CATEGORIES_PROJECT = 'GET_CATEGORIES_PROJECT';
export const SET_CATEGORIES_EMPTY = 'SET_CATEGORIES_EMPTY';
export const GET_CATEGORIES_INSPECTION = 'GET_CATEGORIES_INSPECTION';
export const GET_DEFICIENCIES = 'GET_DEFICIENCIES';
export const GET_MARKINGS_TYPES = 'GET_MARKINGS_TYPES';
export const GET_CATEGORIES_MARKING = 'GET_CATEGORIES_MARKING';
export const GET_CATEGORIES_ACCESS = 'GET_CATEGORIES_ACCESS';
export const GET_ACCESS_TYPES = 'GET_ACCESS_TYPES';
export const GET_ACCESS_TYPE_DETAILS = 'GET_ACCESS_TYPE_DETAILS';
export const SET_LATITUDE = 'SET_LATITUDE';
export const SET_LONGITUDE = 'SET_LONGITUDE';
export const SET_FROM_MAP = 'SET_FROM_MAP';
export const SET_PROJECT_FOR_MAP = 'SET_PROJECT_FOR_MAP';

// Structures
export const GET_STRUCTURES = 'GET_STRUCTURES';
export const CREATE_STRUCTURE = 'CREATE_STRUCTURE';
export const UPDATE_STRUCTURE = 'UPDATE_STRUCTURE';
export const DELETE_STRUCTURE = 'DELETE_STRUCTURE';
export const GET_PHOTOS = 'GET_PHOTOS';
export const GET_ITEMS_STRUCTURE = 'GET_ITEMS_STRUCTURE';
export const ADD_STRUCTURES = 'ADD_STRUCTURES';

// Spams
export const GET_SPAN = 'GET_SPAN';
export const GET_SPANS = 'GET_SPANS';
export const CREATE_SPAM = 'CREATE_SPAM';
export const UPDATE_SPAM = 'UPDATE_SPAM';
export const DELETE_SPAM = 'DELETE_SPAM';
export const GET_PHOTOS_SPAN = 'GET_PHOTOS_SPAN';
export const GET_ITEMS_SPAN = 'GET_ITEMS_SPAN';
export const GET_MARKINGS = 'GET_MARKINGS';
export const GET_ACCESS = 'GET_ACCESS';
export const SET_STRUCTURE_START = 'SET_STRUCTURE_START';
export const SET_STRUCTURE_END = 'SET_STRUCTURE_END';

// Reports
export const GET_REPORTS = 'GET_REPORTS';
export const GET_REPORTS_ERROR = 'GET_REPORTS_ERROR';
export const CREATE_REPORT = 'CREATE_REPORT';
export const CREATE_REPORT_ERROR = 'CREATE_REPORT_ERROR';
export const GET_REPORT = 'GET_REPORT';
export const UPDATE_REPORT = 'UPDATE_REPORT';
export const UPDATE_REPORT_ERROR = 'UPDATE_REPORT_ERROR';
export const DELETE_REPORT = 'DELETE_REPORT';

export const GET_SUBSTATIONS = 'GET_SUBSTATIONS';
export const DELETE_SUBSTATION = 'DELETE_SUBSTATION';

export const GET_SETS = 'GET_SETS';
export const DELETE_SET = 'DELETE_SET';
export const DUPLICATE_SET = 'DUPLICATE_SET';
export const GET_DEFAULT_SET = 'GET_DEFAULT_SET';

export const GET_INTERACTIONS = 'GET_INTERACTIONS';
export const DELETE_INTERACTION = 'DELETE_INTERACTION';



export const HANDLE_FORM = 'HANDLE_FORM';
export const SET_CURRENT_FORM = 'SET_CURRENT_FORM';
